name: configurator_flutter
description: A new Flutter package project.
version: 0.0.40
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  configurator:
    path: ../configurator

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  i18n_extension: ^9.0.2
  google_fonts: ^5.1.0

  parse_color: ^0.0.1
  collection: ^1.17.1
  yaml: ^3.1.2

  slang_flutter: ^3.0.0

  configurator:
    git:
      url: git@github.com:camrongiuliani/configurator.git
      path: configurator
      ref: 0.0.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
