import 'package:configurator/configurator.dart';
import 'package:test/test.dart';

import 'generator_fixture.dart';

void main() {
  const generator = PythonConfigGenerator();

  group('PythonConfigGenerator', () {
    test('emits deterministic scope data and typed grouped accessors', () {
      final output = generator.generate(
        name: 'app_scope',
        configuration: generatorFixture(),
      );
      final reorderedOutput = generator.generate(
        name: 'app_scope',
        configuration: generatorFixture(reversed: true),
      );

      expect(output, reorderedOutput);
      expect(
        output,
        startsWith(
          '# Generated by Configurator. Do not edit.\n'
          'from __future__ import annotations\n',
        ),
      );
      expect(
        output,
        contains('from configurator import ConfigScope, Configuration'),
      );
      expect(
        output,
        contains('from configurator.pydantic_support import ('),
      );
      expect(output, contains('GENERATED_APP_SCOPE = ConfigScope('));
      expect(output, contains('name="__GeneratedAppScope"'));
      expect(output, contains('weight=42'));

      expect(output, contains('"featureEnabled": True'));
      expect(output, contains('def feature_enabled(self) -> bool:'));
      expect(
        output,
        contains('return self._configuration.flag("featureEnabled")'),
      );
      expect(output, contains('def class_(self) -> bool:'));

      expect(output, contains('def hero_logo(self) -> str:'));
      expect(output, contains('def footer_images(self) -> list[str]:'));
      expect(
        output,
        contains('return self._configuration.image_list("footerImages")'),
      );
      expect(output, contains('def route_1(self) -> str:'));
      expect(output, contains('def details_id(self) -> str:'));
      expect(output, contains('return self._configuration.route(2)'));

      expect(output, contains('def heading_large(self) -> float:'));
      expect(output, contains('def card_horizontal(self) -> float:'));
      expect(output, contains('def page_top(self) -> float:'));
      expect(output, contains('def retry_count(self) -> int:'));
      expect(output, contains('def labels(self) -> list[str]:'));
      expect(output, contains('def hero_title(self) -> Mapping[str, Any]:'));
      expect(
        output,
        contains(
          'def welcome_message(self) -> Mapping[str, Mapping[str, str]]:',
        ),
      );
      expect(
        output,
        contains(
          'return self._configuration.current_translations("welcomeMessage")',
        ),
      );

      expect(output, contains('class AppScopeConfig:'));
      expect(output, contains('self.text_styles: AppScopeTextStyles'));
      expect(output, contains('self.translations: AppScopeTranslations'));
    });

    test('emits optional frozen strict Pydantic snapshots', () {
      final output = generator.generate(
        name: 'app_scope',
        configuration: generatorFixture(),
      );

      expect(output, contains('frozen=True'));
      expect(output, contains('strict=True'));
      expect(output, contains('extra="forbid"'));
      expect(
        output,
        contains('class AppScopeFlagsModel(PydanticBaseModel):'),
      );
      expect(output, contains('    feature_enabled: bool'));
      expect(
        output,
        contains('class AppScopeConfigModel(PydanticBaseModel):'),
      );
      expect(output, contains('    flags: AppScopeFlagsModel'));
      expect(output, contains('def snapshot(self) -> AppScopeConfigModel:'));
      expect(output, contains('        require_pydantic()'));
      expect(
        output,
        contains('feature_enabled=self.flags.feature_enabled'),
      );
      expect(output, contains('retry_count=self.misc.retry_count'));
      expect(
        output,
        contains('def to_model(self) -> AppScopeConfigModel:'),
      );
      expect(output, contains('return self.snapshot()'));
    });

    test('escapes portable values without changing canonical keys', () {
      final output = generator.generate(
        name: 'app_scope',
        configuration: generatorFixture(),
      );

      expect(output, contains(r'"brandPrimary": "#12\"34\n"'));
      expect(output, contains(r'"b\\c.svg"'));
      expect(output, contains(r'"dollar": "${value}"'));
      expect(output, contains(r'"quote": "say \"hi\"\nnext"'));
      expect(output, contains(r'"family": "A \"Font\""'));
    });

    test('rejects Python member collisions', () {
      expect(
        () => generator.generate(
          name: 'collision',
          configuration: routeCollisionFixture(),
        ),
        throwsA(
          isA<StateError>().having(
            (error) => error.message,
            'message',
            contains('Python routes identifier collision'),
          ),
        ),
      );
    });

    test('rejects normalized Pydantic BaseModel member names', () {
      const reservedMembers = {
        'modelConfig': 'model_config',
        'modelDump': 'model_dump',
        'json': 'json',
      };

      for (final entry in reservedMembers.entries) {
        expect(
          () => generator.generate(
            name: 'reserved',
            configuration: YamlConfiguration(
              name: 'reserved',
              misc: [YamlSetting(entry.key, true)],
            ),
          ),
          throwsA(
            isA<StateError>()
                .having(
                  (error) => error.message,
                  'message',
                  contains('Python misc key "${entry.key}"'),
                )
                .having(
                  (error) => error.message,
                  'message',
                  contains('reserved Pydantic member "${entry.value}"'),
                ),
          ),
          reason: entry.key,
        );
      }
    });

    test('rejects unsupported image values', () {
      expect(
        () => generator.generate(
          name: 'invalid',
          configuration: YamlConfiguration(
            name: 'invalid',
            images: [
              YamlSetting('broken', [1, 2])
            ],
          ),
        ),
        throwsA(
          isA<StateError>().having(
            (error) => error.message,
            'message',
            contains('String or List<String>'),
          ),
        ),
      );
    });
  });
}
