import 'package:configurator/src/generators/typescript_config_generator.dart';
import 'package:test/test.dart';

import 'generator_fixture.dart';

void main() {
  const generator = TypeScriptConfigGenerator();

  group('TypeScriptConfigGenerator', () {
    test('emits deterministic scope data and typed grouped accessors', () {
      final output = generator.generate(
        name: 'app_scope',
        configuration: generatorFixture(),
      );
      final reorderedOutput = generator.generate(
        name: 'app_scope',
        configuration: generatorFixture(reversed: true),
      );

      expect(output, reorderedOutput);
      expect(
        output,
        startsWith('// Generated by Configurator. Do not edit.\n'),
      );
      expect(
        output,
        contains(
          'import { Configuration, defineScope } from '
          '"configurator-typescript";',
        ),
      );
      expect(
          output, contains('export const generatedAppScope = defineScope({'));
      expect(output, contains('name: "__GeneratedAppScope"'));
      expect(output, contains('weight: 42'));
      expect(output, contains('routes: new Map<number, string>(['));
      expect(output, contains('[1, "/"],'));
      expect(output, contains('[2, "/details/:id"],'));

      expect(output, contains('"featureEnabled": true'));
      expect(output, contains('get featureEnabled(): boolean {'));
      expect(
        output,
        contains('return this.configuration.flag("featureEnabled");'),
      );
      expect(output, contains('get _class(): boolean {'));

      expect(output, contains('get heroLogo(): string {'));
      expect(output, contains('get footerImages(): readonly string[] {'));
      expect(
        output,
        contains('return this.configuration.imageList("footerImages");'),
      );
      expect(output, contains('get route1(): string {'));
      expect(output, contains('get detailsId(): string {'));
      expect(output, contains('return this.configuration.route(2);'));

      expect(output, contains('get headingLarge(): number {'));
      expect(output, contains('get cardHorizontal(): number {'));
      expect(output, contains('get pageTop(): number {'));
      expect(output, contains('get retryCount(): number {'));
      expect(output, contains('get labels(): Array<string> {'));
      expect(
        output,
        contains('get heroTitle(): Readonly<Record<string, unknown>> {'),
      );
      expect(
        output,
        contains(
          'get welcomeMessage(): '
          'Readonly<Record<string, Readonly<Record<string, string>>>> {',
        ),
      );
      expect(
        output,
        contains(
          'return this.configuration.currentTranslations("welcomeMessage");',
        ),
      );

      expect(output, contains('export class AppScopeConfig {'));
      expect(output, contains('readonly textStyles: AppScopeTextStyles;'));
      expect(output, contains('readonly translations: AppScopeTranslations;'));
    });

    test('escapes portable values without changing canonical keys', () {
      final output = generator.generate(
        name: 'app_scope',
        configuration: generatorFixture(),
      );

      expect(output, contains(r'"brandPrimary": "#12\"34\n"'));
      expect(output, contains(r'"b\\c.svg"'));
      expect(output, contains(r'"dollar": "${value}"'));
      expect(output, contains(r'"quote": "say \"hi\"\nnext"'));
      expect(output, contains(r'"family": "A \"Font\""'));
    });

    test('rejects TypeScript member collisions', () {
      expect(
        () => generator.generate(
          name: 'collision',
          configuration: routeCollisionFixture(),
        ),
        throwsA(
          isA<StateError>().having(
            (error) => error.message,
            'message',
            contains('TypeScript routes identifier collision'),
          ),
        ),
      );
    });
  });
}
