import 'package:configurator/configurator.dart';
import 'package:configurator/src/generators/generator_support.dart';

/// Generates a typed Python configuration module from a resolved configuration.
class PythonConfigGenerator {
  const PythonConfigGenerator();

  String generate({
    required String name,
    required YamlConfiguration configuration,
  }) {
    final model = GeneratedConfigModel.fromConfiguration(
      name: name,
      configuration: configuration,
    );
    final buffer = StringBuffer()
      ..writeln('# Generated by Configurator. Do not edit.')
      ..writeln('from __future__ import annotations')
      ..writeln()
      ..writeln('from typing import Any, Mapping')
      ..writeln()
      ..writeln('from configurator import ConfigScope, Configuration')
      ..writeln()
      ..writeln()
      ..writeln('GENERATED_${model.constantName} = ConfigScope(')
      ..writeln('    name=${quotedString(model.scopeName)},')
      ..writeln('    weight=${model.weight},')
      ..writeln(
        '    flags=${_settingsLiteral(model.flags, indent: 4)},',
      )
      ..writeln(
        '    images=${_settingsLiteral(model.images, indent: 4)},',
      )
      ..writeln('    routes=${_routesLiteral(model.routes, indent: 4)},')
      ..writeln(
        '    colors=${_settingsLiteral(model.colors, indent: 4)},',
      )
      ..writeln(
        '    sizes=${_settingsLiteral(model.sizes, indent: 4)},',
      )
      ..writeln(
        '    paddings=${_settingsLiteral(model.paddings, indent: 4)},',
      )
      ..writeln(
        '    margins=${_settingsLiteral(model.margins, indent: 4)},',
      )
      ..writeln('    misc=${_settingsLiteral(model.misc, indent: 4)},')
      ..writeln(
        '    text_styles=${_settingsLiteral(model.textStyles, indent: 4)},',
      )
      ..writeln(
        '    translations=${_settingsLiteral(model.translations, indent: 4)},',
      )
      ..writeln(')')
      ..writeln()
      ..writeln();

    final groups = <_PythonGroup>[
      _PythonGroup(
        suffix: 'Flags',
        fieldName: 'flags',
        accessors: model.flags
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: 'bool',
                expression: '_configuration.flag(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Colors',
        fieldName: 'colors',
        accessors: model.colors
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: 'str',
                expression:
                    '_configuration.color(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Images',
        fieldName: 'images',
        accessors: model.images
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: setting.value is List ? 'list[str]' : 'str',
                expression: setting.value is List
                    ? '_configuration.image_list(${quotedString(setting.key)})'
                    : '_configuration.image(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Routes',
        fieldName: 'routes',
        accessors: model.routes
            .map(
              (route) => _PythonAccessor(
                key: route.path,
                identifierSeed: identifierWords(route.path).isEmpty
                    ? 'route_${route.id}'
                    : route.path,
                returnType: 'str',
                expression: '_configuration.route(${route.id})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Sizes',
        fieldName: 'sizes',
        accessors: model.sizes
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: 'float',
                expression: '_configuration.size(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Paddings',
        fieldName: 'paddings',
        accessors: model.paddings
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: 'float',
                expression:
                    '_configuration.padding(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Margins',
        fieldName: 'margins',
        accessors: model.margins
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: 'float',
                expression:
                    '_configuration.margin(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Misc',
        fieldName: 'misc',
        accessors: model.misc
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: pythonType(setting.value),
                expression: '_configuration.misc(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'TextStyles',
        fieldName: 'text_styles',
        accessors: model.textStyles
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: 'Mapping[str, Any]',
                expression:
                    '_configuration.text_style(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _PythonGroup(
        suffix: 'Translations',
        fieldName: 'translations',
        accessors: model.translations
            .map(
              (setting) => _PythonAccessor(
                key: setting.key,
                returnType: 'Mapping[str, Mapping[str, str]]',
                expression:
                    '_configuration.current_translations(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
    ];

    for (final group in groups) {
      _writeGroup(buffer, model, group);
      buffer
        ..writeln()
        ..writeln();
    }

    _writeRootAccessor(buffer, model, groups);
    return '${buffer.toString().trimRight()}\n';
  }

  void _writeGroup(
    StringBuffer buffer,
    GeneratedConfigModel model,
    _PythonGroup group,
  ) {
    final members = group.accessors
        .map(
          (accessor) => MapEntry(
            accessor.key,
            pythonIdentifier(accessor.identifierSeed ?? accessor.key),
          ),
        )
        .toList();
    ensureMemberIdentifiersUnique(
      members: members,
      language: 'Python',
      group: group.fieldName,
    );

    buffer
      ..writeln('class ${model.pascalName}${group.suffix}:')
      ..writeln('    __slots__ = ("_configuration",)')
      ..writeln()
      ..writeln('    def __init__(self, configuration: Configuration) -> None:')
      ..writeln('        self._configuration = configuration');

    for (var index = 0; index < group.accessors.length; index++) {
      final accessor = group.accessors[index];
      buffer
        ..writeln()
        ..writeln('    @property')
        ..writeln(
          '    def ${members[index].value}(self) -> ${accessor.returnType}:',
        )
        ..writeln('        return self.${accessor.expression}');
    }
  }

  void _writeRootAccessor(
    StringBuffer buffer,
    GeneratedConfigModel model,
    List<_PythonGroup> groups,
  ) {
    buffer
      ..writeln('class ${model.pascalName}Config:')
      ..writeln('    __slots__ = (')
      ..writeln('        "configuration",');
    for (final group in groups) {
      buffer.writeln('        "${group.fieldName}",');
    }
    buffer
      ..writeln('    )')
      ..writeln()
      ..writeln('    def __init__(self, configuration: Configuration) -> None:')
      ..writeln('        self.configuration = configuration');
    for (final group in groups) {
      buffer.writeln(
        '        self.${group.fieldName}: ${model.pascalName}${group.suffix} = '
        '${model.pascalName}${group.suffix}(configuration)',
      );
    }
  }

  String _settingsLiteral(
    List<GeneratedSetting> settings, {
    required int indent,
  }) {
    return pythonLiteral(
      <String, Object?>{
        for (final setting in settings) setting.key: setting.value,
      },
      indent: indent,
    );
  }

  String _routesLiteral(List<GeneratedRoute> routes, {required int indent}) {
    if (routes.isEmpty) return '{}';
    final childIndent = indent + 4;
    final lines = routes
        .map(
          (route) =>
              '${' ' * childIndent}${route.id}: ${quotedString(route.path)},',
        )
        .join('\n');
    return '{\n$lines\n${' ' * indent}}';
  }
}

class _PythonGroup {
  const _PythonGroup({
    required this.suffix,
    required this.fieldName,
    required this.accessors,
  });

  final String suffix;
  final String fieldName;
  final List<_PythonAccessor> accessors;
}

class _PythonAccessor {
  const _PythonAccessor({
    required this.key,
    required this.returnType,
    required this.expression,
    this.identifierSeed,
  });

  final String key;
  final String returnType;
  final String expression;
  final String? identifierSeed;
}
