import 'package:configurator/configurator.dart';
import 'package:configurator/src/generators/generator_support.dart';

/// Generates a typed TypeScript configuration module from a resolved config.
class TypeScriptConfigGenerator {
  const TypeScriptConfigGenerator();

  String generate({
    required String name,
    required YamlConfiguration configuration,
  }) {
    final model = GeneratedConfigModel.fromConfiguration(
      name: name,
      configuration: configuration,
    );
    final buffer = StringBuffer()
      ..writeln('// Generated by Configurator. Do not edit.')
      ..writeln(
        'import { Configuration, defineScope } from "configurator-typescript";',
      )
      ..writeln()
      ..writeln('export const generated${model.pascalName} = defineScope({')
      ..writeln('  name: ${quotedString(model.scopeName)},')
      ..writeln('  weight: ${model.weight},')
      ..writeln('  flags: ${_settingsLiteral(model.flags, indent: 2)},')
      ..writeln('  images: ${_settingsLiteral(model.images, indent: 2)},')
      ..writeln('  routes: ${_routesLiteral(model.routes, indent: 2)},')
      ..writeln('  colors: ${_settingsLiteral(model.colors, indent: 2)},')
      ..writeln('  sizes: ${_settingsLiteral(model.sizes, indent: 2)},')
      ..writeln(
        '  paddings: ${_settingsLiteral(model.paddings, indent: 2)},',
      )
      ..writeln('  margins: ${_settingsLiteral(model.margins, indent: 2)},')
      ..writeln('  misc: ${_settingsLiteral(model.misc, indent: 2)},')
      ..writeln(
        '  textStyles: ${_settingsLiteral(model.textStyles, indent: 2)},',
      )
      ..writeln(
        '  translations: ${_settingsLiteral(model.translations, indent: 2)},',
      )
      ..writeln('});')
      ..writeln()
      ..writeln();

    final groups = <_TypeScriptGroup>[
      _TypeScriptGroup(
        suffix: 'Flags',
        fieldName: 'flags',
        accessors: model.flags
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType: 'boolean',
                expression:
                    'this.configuration.flag(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Colors',
        fieldName: 'colors',
        accessors: model.colors
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType: 'string',
                expression:
                    'this.configuration.color(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Images',
        fieldName: 'images',
        accessors: model.images
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType:
                    setting.value is List ? 'readonly string[]' : 'string',
                expression: setting.value is List
                    ? 'this.configuration.imageList(${quotedString(setting.key)})'
                    : 'this.configuration.image(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Routes',
        fieldName: 'routes',
        accessors: model.routes
            .map(
              (route) => _TypeScriptAccessor(
                key: route.path,
                identifierSeed: identifierWords(route.path).isEmpty
                    ? 'route_${route.id}'
                    : route.path,
                returnType: 'string',
                expression: 'this.configuration.route(${route.id})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Sizes',
        fieldName: 'sizes',
        accessors: model.sizes
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType: 'number',
                expression:
                    'this.configuration.size(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Paddings',
        fieldName: 'paddings',
        accessors: model.paddings
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType: 'number',
                expression:
                    'this.configuration.padding(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Margins',
        fieldName: 'margins',
        accessors: model.margins
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType: 'number',
                expression:
                    'this.configuration.margin(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Misc',
        fieldName: 'misc',
        accessors: model.misc
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType: typeScriptType(setting.value),
                expression:
                    'this.configuration.misc(${quotedString(setting.key)}) as '
                    '${typeScriptType(setting.value)}',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'TextStyles',
        fieldName: 'textStyles',
        accessors: model.textStyles
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType: 'Readonly<Record<string, unknown>>',
                expression:
                    'this.configuration.textStyle(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
      _TypeScriptGroup(
        suffix: 'Translations',
        fieldName: 'translations',
        accessors: model.translations
            .map(
              (setting) => _TypeScriptAccessor(
                key: setting.key,
                returnType:
                    'Readonly<Record<string, Readonly<Record<string, string>>>>',
                expression:
                    'this.configuration.currentTranslations(${quotedString(setting.key)})',
              ),
            )
            .toList(),
      ),
    ];

    for (final group in groups) {
      _writeGroup(buffer, model, group);
      buffer
        ..writeln()
        ..writeln();
    }

    _writeRootAccessor(buffer, model, groups);
    return '${buffer.toString().trimRight()}\n';
  }

  void _writeGroup(
    StringBuffer buffer,
    GeneratedConfigModel model,
    _TypeScriptGroup group,
  ) {
    final members = group.accessors
        .map(
          (accessor) => MapEntry(
            accessor.key,
            typeScriptIdentifier(accessor.identifierSeed ?? accessor.key),
          ),
        )
        .toList();
    ensureMemberIdentifiersUnique(
      members: members,
      language: 'TypeScript',
      group: group.fieldName,
    );

    buffer
      ..writeln('export class ${model.pascalName}${group.suffix} {')
      ..writeln(
        '  constructor(private readonly configuration: Configuration) {}',
      );
    for (var index = 0; index < group.accessors.length; index++) {
      final accessor = group.accessors[index];
      buffer
        ..writeln()
        ..writeln(
          '  get ${members[index].value}(): ${accessor.returnType} {',
        )
        ..writeln('    return ${accessor.expression};')
        ..writeln('  }');
    }
    buffer.writeln('}');
  }

  void _writeRootAccessor(
    StringBuffer buffer,
    GeneratedConfigModel model,
    List<_TypeScriptGroup> groups,
  ) {
    buffer.writeln('export class ${model.pascalName}Config {');
    for (final group in groups) {
      buffer.writeln(
        '  readonly ${group.fieldName}: '
        '${model.pascalName}${group.suffix};',
      );
    }
    buffer
      ..writeln()
      ..writeln('  constructor(readonly configuration: Configuration) {');
    for (final group in groups) {
      buffer.writeln(
        '    this.${group.fieldName} = '
        'new ${model.pascalName}${group.suffix}(configuration);',
      );
    }
    buffer
      ..writeln('  }')
      ..writeln('}');
  }

  String _settingsLiteral(
    List<GeneratedSetting> settings, {
    required int indent,
  }) {
    return typeScriptLiteral(
      <String, Object?>{
        for (final setting in settings) setting.key: setting.value,
      },
      indent: indent,
    );
  }

  String _routesLiteral(List<GeneratedRoute> routes, {required int indent}) {
    if (routes.isEmpty) return 'new Map<number, string>()';
    final childIndent = indent + 2;
    final lines = routes
        .map(
          (route) =>
              '${' ' * childIndent}[${route.id}, ${quotedString(route.path)}],',
        )
        .join('\n');
    return 'new Map<number, string>([\n$lines\n${' ' * indent}])';
  }
}

class _TypeScriptGroup {
  const _TypeScriptGroup({
    required this.suffix,
    required this.fieldName,
    required this.accessors,
  });

  final String suffix;
  final String fieldName;
  final List<_TypeScriptAccessor> accessors;
}

class _TypeScriptAccessor {
  const _TypeScriptAccessor({
    required this.key,
    required this.returnType,
    required this.expression,
    this.identifierSeed,
  });

  final String key;
  final String returnType;
  final String expression;
  final String? identifierSeed;
}
