name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependency_overrides:
  configurator:
    path: ../configurator

  configurator_flutter:
    path: ../configurator_flutter

  configurator_annotations:
    path: ../configurator_annotations

  configurator_builder:
    path: ../configurator_builder

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  parse_color: ^0.0.1
  get_it: ^7.2.0
  v_widgets: ^0.0.1+1


  configurator:
    git:
      url: git@github.com:camrongiuliani/configurator.git
      path: configurator

  configurator_flutter:
    git:
      url: git@github.com:camrongiuliani/configurator.git
      path: configurator_flutter

  configurator_annotations:
    git:
      url: git@github.com:camrongiuliani/configurator.git
      path: configurator_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

  configurator_builder:
    git:
      url: git@github.com:camrongiuliani/configurator.git
      path: configurator_builder

flutter:
  uses-material-design: true
  assets:
    - assets/example1.yaml
    - assets/example2.yaml
