name: configurator_builder
description: Generate Configurations from YAML
version: 0.0.1+2
homepage: https://github.com/camrongiuliani/maestro

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  analyzer: ^4.1.0
  build: ^2.2.1
  yaml: ^3.1.1
  color: ^3.0.0

  configurator:
    git:
      url: git@github.com:camrongiuliani/configurator.git
      path: configurator

  configurator_annotations:
    git:
      url: git@github.com:camrongiuliani/configurator.git
      path: configurator_annotations

  meta: ^1.7.0
  source_gen: ^1.2.1
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  generator_test: ^0.1.0
  json_annotation: ^4.4.0
  test: ^1.16.0
  very_good_analysis: ^2.4.0
  build_resolvers: ^2.0.10

import_sorter:
  comments: false