// // Generated by Configurator - DO NOT MODIFY BY HAND
// @generated

import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:collection/collection.dart';
import 'package:configurator_flutter/configurator_flutter.dart';

// ********************************
// ignore_for_file: type=lint
// ********************************

// ********************************
// Enums
// ********************************

// ********************************
// Keys
// ********************************

class _FlagKeys {
  const _FlagKeys();
}

class _ImageKeys {
  const _ImageKeys();

  final footerImages = 'footerImages';
}

class _MiscKeys {
  const _MiscKeys();
}

class _TextStyleKeys {
  const _TextStyleKeys();
}

class ImageArrayRouteKeys {
  const ImageArrayRouteKeys();

  final master = 1;

  final test = 4;
}

class _SizeKeys {
  const _SizeKeys();
}

class _PaddingKeys {
  const _PaddingKeys();
}

class _MarginKeys {
  const _MarginKeys();
}

class _ColorKeys {
  const _ColorKeys();
}

class _EnumKeys {
  const _EnumKeys();
}

class ImageArrayConfigKeys {
  const ImageArrayConfigKeys();

  static final routes = const ImageArrayRouteKeys();

  static final flags = const _FlagKeys();

  static final sizes = const _SizeKeys();

  static final padding = const _PaddingKeys();

  static final margins = const _MarginKeys();

  static final misc = const _MiscKeys();

  static final textStyles = const _TextStyleKeys();

  static final colors = const _ColorKeys();

  static final images = const _ImageKeys();

  static final enums = const _EnumKeys();
}

// ********************************
// Theme
// ********************************

class GeneratedImageArrayThemeExtension
    extends ConfigTheme<GeneratedImageArrayThemeExtension> {
  GeneratedImageArrayThemeExtension({required super.themeMap});

  @override
  GeneratedImageArrayThemeExtension copyWith({
    Map<String, Map<String, dynamic>>? themeMap,
  }) {
    this.themeMap.addAll(themeMap ?? {});
    return GeneratedImageArrayThemeExtension(themeMap: this.themeMap);
  }

  @override
  GeneratedImageArrayThemeExtension lerp(
    ThemeExtension<GeneratedImageArrayThemeExtension>? other,
    double t,
  ) {
    if (other is! GeneratedImageArrayThemeExtension) {
      return this;
    }
    return GeneratedImageArrayThemeExtension(themeMap: themeMap);
  }
}

// ********************************
// Flags
// ********************************

class _FlagAccessor {
  const _FlagAccessor(this._config);

  final Configuration _config;
}

// ********************************
// Enums
// ********************************

class _EnumAccessor {
  const _EnumAccessor(this._config);

  final Configuration _config;
}

// ********************************
// Images
// ********************************

class _ImageAccessor {
  const _ImageAccessor(this._config);

  final Configuration _config;

  List<String> get footerImages => _config.imageList("footerImages");
}

// ********************************
// Routes
// ********************************

class _RouteAccessor {
  const _RouteAccessor(this._config);

  final Configuration _config;

  String get master => _config.route(1);

  String get test => _config.route(4);
}

// ********************************
// Colors
// ********************************

class _ColorAccessor {
  const _ColorAccessor(this._config);

  final Configuration _config;
}

// ********************************
// Sizes
// ********************************

class _SizeAccessor {
  const _SizeAccessor(this._config);

  final Configuration _config;
}

// ********************************
// Padding
// ********************************

class _PaddingAccessor {
  const _PaddingAccessor(this._config);

  final Configuration _config;
}

// ********************************
// Margins
// ********************************

class _MarginAccessor {
  const _MarginAccessor(this._config);

  final Configuration _config;
}

// ********************************
// Misc
// ********************************

class _MiscAccessor {
  const _MiscAccessor(this._config);

  final Configuration _config;
}

// ********************************
// TextStyles
// ********************************

class _TextStyleAccessor {
  const _TextStyleAccessor(this._config);

  final Configuration _config;

  Map<String, String> get typefaces {
    return {};
  }
}

// ********************************
// Strings
// ********************************

class _I18nDart {
  _I18nDart(this._config);

  final Configuration _config;

  // Translations
}

// ********************************
// Configuration
// ********************************

class GeneratedImageArray extends ConfigScope {
  const GeneratedImageArray();

  @override
  final String name = "__GeneratedImageArray";

  @override
  final int weight = 0;

  @override
  final Map<String, bool> flags = const {};

  @override
  final Map<String, dynamic> images = const {
    "footerImages": [
      'assets/FDIC1.svg',
      'assets/FDIC2.svg',
      'assets/FDIC3.svg',
    ],
  };

  @override
  final Map<String, String> colors = const {};

  @override
  final Map<String, double> sizes = const {};

  @override
  final Map<String, double> padding = const {};

  @override
  final Map<String, double> margins = const {};

  @override
  final Map<String, dynamic> misc = const {};

  @override
  final Map<String, dynamic> textStyles = const {};

  @override
  final Map<int, String> routes = const {1: '/master', 4: 'test'};

  @override
  final Map<String, String> enums = const {};

  @override
  final Map<String, Map<String, String>> translations = const {};
}

// ********************************
// Configuration Extension
// ********************************

extension ConfigAccessor on Configuration {
  _FlagAccessor get flags => _FlagAccessor(this);

  _ColorAccessor get colors => _ColorAccessor(this);

  _ImageAccessor get images => _ImageAccessor(this);

  _SizeAccessor get sizes => _SizeAccessor(this);

  _PaddingAccessor get paddings => _PaddingAccessor(this);

  _MarginAccessor get margins => _MarginAccessor(this);

  _MiscAccessor get miscellaneous => _MiscAccessor(this);

  _EnumAccessor get enums => _EnumAccessor(this);

  _TextStyleAccessor get textStyles => _TextStyleAccessor(this);

  _RouteAccessor get routes => _RouteAccessor(this);

  _I18nDart get strings => _I18nDart(this);
}
